### ISSUE TITLE
Make depends on Graph, which now depends on Set::Object, which can pull in Moose

### ISSUE THREAD

**Issue by briandfoy** [klp2/Make#12]
I wrote about this in https://github.com/graphviz-perl/Graph/issues/17 too. Basically, this has turned into a heavyweight module now.

Looking at the code quickly, it looks that there's only a limited use for Graph. Maybe it can be lazily loaded if it's available rather than requiring the module.

But, since the use here is very simple, maybe it should be internal to the module.

**Comment by mohawk2** [comment]
In due course the plan is to have Graph be fundamental to how the module operates, so this would only be a temporary solution. As suggested on the other issue, your particular itch would be best scratched by either fixing your CI, or getting Set::Object to stop recommending Moose.

**Comment by mohawk2** [comment]
In particular, even if Graph were to be removed as a runtime.requires, it would obviously need to be added as a runtime.recommends, which would leave you in exactly the same position.

**Comment by briandfoy** [comment]
It's not that my CI is broken. It's doing exactly what it should, and it's turned up this issue that's important to me and my users. I'm not hiding this stuff in testing. It's that this can happen to users installing and managing all this. Previously, there was a lightweight module, and now it seems like it's half of CPAN.

I'll just drop this module though. I don't think it's particularly polite practice to suddenly start changing modules that have been stable for a decade or more. I think it would be much better to leave them alone and fork.

Again, that's just feedback from actual community use.
