### ISSUE TITLE
pmake conflicts with Debian pmake

### ISSUE THREAD

**Issue by plicease** [klp2/Make#6]
`pmake` is the name of the FreeBSD make (although it is invoked there as just `make`).  On Debian the BSD make is invoked as `pmake` which conflicts with the script that comes with this distribution.  There should be an option when installing to not install the pure perl pmake or to install it under a different name.  I would even argue that it might be better to use a completely different name.

**Comment by klp2** [comment]
A different name makes sense to me.

Maybe just 'pure-perl-make'. Kind of annoying to type, but I suspect that the script's name is not being typed very often.

**Comment by klp2** [comment]
A new version with the renamed script should be available on CPAN soon. Thanks for pointing this out.
