### ISSUE TITLE
Module takeover?

### ISSUE THREAD

**Issue by mohawk2** [klp2/Make#8]
Would you like to transfer the repository over to me? I've already requested of the PAUSE Gods to be granted PAUSE permissions, I'd just prefer to keep the repo unitary rather than forking it.

**Comment by klp2** [comment]
I think I accidentally left the `ADOPTME` status from when I first took over the module. I hadn't intended to give up on them, and intended to respond to issues/PR's and such, and any work that might be required for perl 7. That being said, I'm very rarely actually using the module, so you now have first-come permissions on the relevant PAUSE namespaces, with my self listed as a co-maintainer. I'd prefer to keep the repo here, but have sent an collaborator invite, which I think lets you do everything that is useful outside of adding additional collaborators. Does that seem ok?

**Comment by mohawk2** [comment]
I've accepted (and seen the PAUSE perms, thanks). It seems a bit halfway to have the main PAUSE control different from the repo control, but I don't see it's a problem for the present!

**Comment by mohawk2** [comment]
By the way, do you mind my rebasing the history of this against https://github.com/gitpan/Make ? I'll put tags on so the CPAN releases since you took over are still correctly tagged, but it will involve a one-time force-push on `master`.

Also, there's a 1.2.0 version on CPAN which isn't reflected in the repo - could you push what you did for that? :-)

**Comment by klp2** [comment]
The rebase would be great, thanks!

https://github.com/klp2/Make/pull/7 was the update to 1.2.0, I'm not sure why I didn't merge that before, but that has been fixed now.

**Comment by mohawk2** [comment]
Seen, thanks! I don't see a tag or the version update, can you confirm you haven't got any uncommitted changes there? I'm happy to do any fixups beyond that to make sure our repo reflects current CPAN before doing the above rebasing :-)

**Comment by klp2** [comment]
Sorry for the slow response, I believe there were no more uncommitted changes there.

My slow response here seems to point to transferring the repo over to you making sense, would you still want to go ahead with that?

**Comment by mohawk2** [comment]
I checked your pushed updated version against CPAN 1.2.0, and there were no differences, so all is good.

Yes, please do transfer the repo to my ownership :-)

**Comment by mohawk2** [comment]
I checked your pushed updated version against CPAN 1.2.0, and there were no differences, so all is good.

Yes, please do transfer the repo to my ownership :-)
